# A pod to schedule on on particula node throught node selector.
# https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/  

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: ckad-2023
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    node: ckad