apiVersion: v1
kind: Pod
metadata:
  name: args-cmds
spec:
  containers:
  - name: ubuntu
    image: ubuntu-sleeper
# EEither can be used   command: ["sleep","5000"]
    command: ["sleep"]
    args: ["5000"]