# https://kubernetes.io/docs/concepts/configuration/secret/
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-vol-pod
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: mysecret
  containers:
    - name: dotfile-test-container
      image: registry.k8s.io/busybox
      command:
        - ls
        - "-l"
        - "/etc/secret-volume"
      volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/etc/secret-volume"
# secrets are not encrypted . only encoded
# Do not check-in secret to the SCM
# We can encrypt the secrets where it got stored in etcd. # By default it will encrypt.
# secrets can be viewed anyone who acces to create pods in ns.
# consider creating RBAC
# consider third party solutions - vault.          