apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  DB_password: xyzljsfjn435  # Encoded secret # echo -n 'mysqlpass' | base64 -encode
  DB_user: root 
# k create secret generic <s.n> --from-lieteral=<key>=<value> --from-lieteral=<key>=<value>
#  k create secret generic <s.n> --from-file=<path to file>
# k create secret generic <s.n> --from-file=app_secret.properties 

