#https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
---
apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
spec:
  securityContext:  # pod level sec-ctx set - applies to each container
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  volumes:
  - name: sec-ctx-vol
    emptyDir: {}
  containers:
  - name: sec-ctx-demo
    image: busybox:1.28
    command: [ "sh", "-c", "sleep 1h" ]
    volumeMounts:
    - name: sec-ctx-vol
      mountPath: /data/demo
    securityContext:
      allowPrivilegeEscalation: false

      
