#Ref https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/
# In k8s sa are namespaced. each ns have their own sa, can be identical on the two ns.
# A ServiceAccount controller manages the ServiceAccounts inside namespaces, 
#and ensures a ServiceAccount named "default" exists in every active namespace

apiVersion: apps/v1 # this apiVersion is relevant as of Kubernetes 1.9
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  replicas: 3
  template:
    metadata:
    # ...
    spec:
      serviceAccountName: bob-the-bot
      containers:
      - name: nginx
        image: nginx:1.14.2

    # kubectl create serviceaccount jenkins
    # kubectl create token jenkins    