---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-app
spec:
  replicas: 5
  selector:
    matchLabels:
      name: go-webapp
  template:
    metadata:
      labels:
        name: go-webapp
    spec:
      containers:
      - name: application
        image: docker.io/nsudhakar/ckad-projets/go-web
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000