---
apiVersion: v1
kind: Service
metadata:
  name: go-web-service
  namespace: ckad-2023
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    name: go-webapp