#In Kubernetes, a Service is a method for exposing a network application that is running as one or more Pods in your cluster.

# just like other object in k8
# Service Types
# 1. NodePort   2. ClusterIp   3. LoadBalancer

#>1.NodePot
# > External access of the service - NodePort -range   (30000-32767)
# > Target port = container port where its exposing
# >  port = service port where its getting traffic from pod.
# > use selector to select the pod.
# > algorithm= Random
# > Access the service using node IP with nodeport.

#>2. ClusterIP
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: proxy
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports:
      - containerPort: 80
        name: http-web-svc

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app.kubernetes.io/name: proxy
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc