# types of workloads
# perform a certain task and finish.
#A container always restarts if it exits.. since k8s by default keep the restartPolicy=Always for a Pod.
==> We can set explictily: restartPolic: Never
#=======================================================================
# k create job

apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl:5.34.0
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4 # To prevent job from quitting before it succeeds

  # how many attempts it took  == > check for Succeeded & Failed counts by describing the pod.
  # How many attempts did it took
  #> k describe job <job> | grep succeeded & failed.

