# kubectl get pods --selector app=App1
#Ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/label
apiVersion: v1
kind: Pod
metadata:
  name: label-demo
  labels:
    environment: production
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80

#kubectl get pods -l environment=production,tier=frontend
#kubectl get pods -l app=nginx -L tier

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend # must use in template
  template:
    metadata:
      labels:
        tier: frontend  # same as selector
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google_samples/gb-frontend:v3